### PR TITLE
refactor: remove redundant cmake definition

### PR DESCRIPTION
**Pull request by wep21**
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Review by youtalk — APPROVED** [review]
LGTM
But we need to fix the `cpplint` problem https://results.pre-commit.ci/run/github/791833089/1719813784.vF-W1qiuSbyweopfbpNS9Q.
@wep21 Could you fix them?

**Review by esteve — APPROVED** [review]
@wep21 LGTM, thanks. Optionally, if you want, you can move the header files to the `src` folder and keep them private if there are no downstream packages that depend on these headers.

**Comment by youtalk** [comment]
> LGTM But we need to fix the `cpplint` problem https://results.pre-commit.ci/run/github/791833089/1719813784.vF-W1qiuSbyweopfbpNS9Q. @wep21 Could you fix them?

This was solved by https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/15.

**Pull request merged**
